import { MatchUser } from '@/types/matching';

export const mockRecommendedUsers: MatchUser[] = [
  {
    id: '1',
    name: '김민지',
    age: 21,
    gender: '여성',
    grade: 2,
    bio: '깔끔하고 조용한 환경을 선호합니다. 밤 11시 이전에 자요.',
    tags: ['깔끔함', '조용함', '아침형'],
    compatibility: 92,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: '이준호',
    age: 22,
    gender: '남성',
    grade: 3,
    bio: '책을 많이 읽고 도서관을 자주 가요. 조용한 분과 지내고 싶습니다.',
    tags: ['조용함', '책벌레', '아침형'],
    compatibility: 88,
    createdAt: '2024-01-14',
  },
  {
    id: '3',
    name: '박지연',
    age: 20,
    gender: '여성',
    grade: 1,
    bio: '깔끔함을 중요하게 생각해요. 매주 청소하며 생활합니다.',
    tags: ['깔끔함', '운동', '규칙적'],
    compatibility: 85,
    createdAt: '2024-01-13',
  },
  {
    id: '4',
    name: '최현준',
    age: 23,
    gender: '남성',
    grade: 4,
    bio: '조용히 자신의 일에 집중하는 스타일입니다.',
    tags: ['조용함', '집중력', '아침형'],
    compatibility: 82,
    createdAt: '2024-01-12',
  },
  {
    id: '5',
    name: '이서윤',
    age: 21,
    gender: '여성',
    grade: 2,
    bio: '함께 운동하고 건강한 생활을 하고 싶습니다!',
    tags: ['운동', '활발함', '건강'],
    compatibility: 78,
    createdAt: '2024-01-11',
  },
  {
    id: '6',
    name: '정우성',
    age: 22,
    gender: '남성',
    grade: 3,
    bio: '음악을 좋아하고 악기를 연주합니다. 소음 이웃에게 사과합니다😅',
    tags: ['예술', '음악', '밤형'],
    compatibility: 72,
    createdAt: '2024-01-10',
  },
];

export const mockWaitingMatches: MatchUser[] = [
  {
    id: '7',
    name: '홍명진',
    age: 20,
    gender: '남성',
    grade: 1,
    bio: '반갑습니다! 룸메이트를 찾고 있습니다.',
    tags: ['친절함', '활발함'],
    compatibility: 75,
    createdAt: '2024-01-09',
  },
  {
    id: '8',
    name: '김혜은',
    age: 21,
    gender: '여성',
    grade: 2,
    bio: '성격이 밝고 긍정적입니다.',
    tags: ['밝음', '친구같은'],
    compatibility: 70,
    createdAt: '2024-01-08',
  },
];

export const mockReceivedRequests: MatchUser[] = [
  {
    id: '9',
    name: '박준영',
    age: 23,
    gender: '남성',
    grade: 3,
    bio: '조용하고 차분한 성격입니다.',
    tags: ['차분함', '배려심'],
    compatibility: 81,
    createdAt: '2024-01-07',
  },
  {
    id: '10',
    name: '신지은',
    age: 20,
    gender: '여성',
    grade: 1,
    bio: '새로운 친구를 사귀고 싶습니다.',
    tags: ['친근함', '개방적'],
    compatibility: 76,
    createdAt: '2024-01-06',
  },
  {
    id: '11',
    name: '정수현',
    age: 22,
    gender: '남성',
    grade: 2,
    bio: '함께 좋은 시간을 보냈으면 좋겠습니다.',
    tags: ['성실함', '따뜻함'],
    compatibility: 79,
    createdAt: '2024-01-05',
  },
];
